"""empty message

Revision ID: 49faf7111f1b
Revises: 
Create Date: 2023-12-14 13:11:46.845190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49faf7111f1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('gameStatus', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
