"""empty message

Revision ID: ea66eb4c8bac
Revises: a46ab43f40bf
Create Date: 2024-01-09 13:31:08.823603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea66eb4c8bac'
down_revision = 'a46ab43f40bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gamename', sa.String(length=50), nullable=False),
    sa.Column('gamedescription', sa.String(length=100), nullable=False),
    sa.Column('gamelocation', sa.String(length=50), nullable=False),
    sa.Column('gamestarttime', sa.DateTime(), nullable=False),
    sa.Column('gamemaster', sa.String(length=50), nullable=False),
    sa.Column('gameassistant', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
